### PR TITLE
master

### PR DESCRIPTION
**Pull request by iamanikeev**
Get rid of Pandas deprecation warning

### CODE REVIEW

**Comment by iamanikeev** [comment]
Hi there! the `.ix` method in Pandas dataframe has been deprecated, so I got a lot of deprecation warnings in a project that uses this package. Hence, this PR. Please let me know whether I miss something, or should the tests be corrected as well (they still use the `.ix` method in `sf` object, maybe it makes sense to remove this method from StyleFrame as well?)

**Comment by DeepSpace2** [comment]
@iamanikeev Thanks for contributing! I will have a look at it later today and merge it into the next release (1.1.2).

One small request: it would be easier for me if next time you can fork and pull request from the devel branch and not the master, thanks! :)

**Comment by iamanikeev** [comment]
> it would be easier for me if next time you can fork and pull request from the devel branch and not the master, thanks! :)
Oops, sorry for that. I can re-fork it as required and make another PR)

**Comment by DeepSpace2** [comment]
> Oops, sorry for that. I can re-fork it as required and make another PR)

That would be greatly appreciated! :+1

**Comment by DeepSpace2** [comment]
Closed since a new PR will be submitted in correct branch (devel).

**Pull request closed without merging**
